//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroCenter.Lingue {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lingua {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lingua() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroCenter.Lingue.Lingua", typeof(Lingua).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Discontinuo.
        /// </summary>
        internal static string A_Discontinuo {
            get {
                return ResourceManager.GetString("A_Discontinuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mix.
        /// </summary>
        internal static string A_Mix {
            get {
                return ResourceManager.GetString("A_Mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Musica.
        /// </summary>
        internal static string A_Musica {
            get {
                return ResourceManager.GetString("A_Musica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RainBow.
        /// </summary>
        internal static string A_RainBow {
            get {
                return ResourceManager.GetString("A_RainBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spento.
        /// </summary>
        internal static string A_Spento {
            get {
                return ResourceManager.GetString("A_Spento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperatura.
        /// </summary>
        internal static string A_Temperatura {
            get {
                return ResourceManager.GetString("A_Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transizione.
        /// </summary>
        internal static string A_Transizione {
            get {
                return ResourceManager.GetString("A_Transizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Animazioni RGB.
        /// </summary>
        internal static string animazioniRGB {
            get {
                return ResourceManager.GetString("animazioniRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Colore.
        /// </summary>
        internal static string colore {
            get {
                return ResourceManager.GetString("colore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dati Seriali.
        /// </summary>
        internal static string datiSeriali {
            get {
                return ResourceManager.GetString("datiSeriali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Donazioni.
        /// </summary>
        internal static string donazioni {
            get {
                return ResourceManager.GetString("donazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dissipatore.
        /// </summary>
        internal static string EL_Dissipatore {
            get {
                return ResourceManager.GetString("EL_Dissipatore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HUB.
        /// </summary>
        internal static string EL_HUB {
            get {
                return ResourceManager.GetString("EL_HUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scheda Video.
        /// </summary>
        internal static string EL_SchedaVideo {
            get {
                return ResourceManager.GetString("EL_SchedaVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Striscia LED.
        /// </summary>
        internal static string EL_StrisciaLED {
            get {
                return ResourceManager.GetString("EL_StrisciaLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ventole.
        /// </summary>
        internal static string EL_Ventole {
            get {
                return ResourceManager.GetString("EL_Ventole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Arduino.
        /// </summary>
        internal static string fArduino {
            get {
                return ResourceManager.GetString("fArduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connessione.
        /// </summary>
        internal static string fConnessione {
            get {
                return ResourceManager.GetString("fConnessione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GitHub.
        /// </summary>
        internal static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Arancione.
        /// </summary>
        internal static string H_Arancione {
            get {
                return ResourceManager.GetString("H_Arancione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bianco.
        /// </summary>
        internal static string H_Bianco {
            get {
                return ResourceManager.GetString("H_Bianco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blu.
        /// </summary>
        internal static string H_Blu {
            get {
                return ResourceManager.GetString("H_Blu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Celeste.
        /// </summary>
        internal static string H_Celeste {
            get {
                return ResourceManager.GetString("H_Celeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fucsia.
        /// </summary>
        internal static string H_Fucsia {
            get {
                return ResourceManager.GetString("H_Fucsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giallo.
        /// </summary>
        internal static string H_Giallo {
            get {
                return ResourceManager.GetString("H_Giallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rosso.
        /// </summary>
        internal static string H_Rosso {
            get {
                return ResourceManager.GetString("H_Rosso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verde.
        /// </summary>
        internal static string H_Verde {
            get {
                return ResourceManager.GetString("H_Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        internal static string impostazioni {
            get {
                return ResourceManager.GetString("impostazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info Creatore.
        /// </summary>
        internal static string infoCreatore {
            get {
                return ResourceManager.GetString("infoCreatore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info Sorgente.
        /// </summary>
        internal static string infoSorgente {
            get {
                return ResourceManager.GetString("infoSorgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ko-Fi.
        /// </summary>
        internal static string ko_fi {
            get {
                return ResourceManager.GetString("ko-fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lingua App.
        /// </summary>
        internal static string linguaApp {
            get {
                return ResourceManager.GetString("linguaApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luminosità.
        /// </summary>
        internal static string lum {
            get {
                return ResourceManager.GetString("lum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manuale.
        /// </summary>
        internal static string manuale {
            get {
                return ResourceManager.GetString("manuale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica il Tema.
        /// </summary>
        internal static string modificailTema {
            get {
                return ResourceManager.GetString("modificailTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica Lingua.
        /// </summary>
        internal static string modificaLingua {
            get {
                return ResourceManager.GetString("modificaLingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dispositivo.
        /// </summary>
        internal static string nomeDispositivo {
            get {
                return ResourceManager.GetString("nomeDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MicroCenter.
        /// </summary>
        internal static string nomeprogetto {
            get {
                return ResourceManager.GetString("nomeprogetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RPM.
        /// </summary>
        internal static string rpm {
            get {
                return ResourceManager.GetString("rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona Colore.
        /// </summary>
        internal static string selezionaColore {
            get {
                return ResourceManager.GetString("selezionaColore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona Dispositivo.
        /// </summary>
        internal static string selezionaDispositivo {
            get {
                return ResourceManager.GetString("selezionaDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stato Collegamento.
        /// </summary>
        internal static string statoCollegamento {
            get {
                return ResourceManager.GetString("statoCollegamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disconnesso.
        /// </summary>
        internal static string statoConnessioneNo {
            get {
                return ResourceManager.GetString("statoConnessioneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connesso.
        /// </summary>
        internal static string statoConnessioneSi {
            get {
                return ResourceManager.GetString("statoConnessioneSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Supporta con un Caffè.
        /// </summary>
        internal static string supportoDonazione {
            get {
                return ResourceManager.GetString("supportoDonazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Telegram.
        /// </summary>
        internal static string telegram {
            get {
                return ResourceManager.GetString("telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tema.
        /// </summary>
        internal static string tema {
            get {
                return ResourceManager.GetString("tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Velocità.
        /// </summary>
        internal static string velocità {
            get {
                return ResourceManager.GetString("velocità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Velocità Ventole.
        /// </summary>
        internal static string velocitàVentole {
            get {
                return ResourceManager.GetString("velocitàVentole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Youtube.
        /// </summary>
        internal static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
    }
}
